# Generated by Django 5.2.4 on 2025-07-12 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LokasiKuliner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('deskripsi', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_produk_lokal', models.BooleanField(default=False, verbose_name='Label Produk Lokal')),
                ('is_resep_asli', models.BooleanField(default=False, verbose_name='Label Resep Asli')),
            ],
        ),
        migrations.CreateModel(
            name='JalurRasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jalur', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('lokasi', models.ManyToManyField(related_name='jalur', to='kuliner.lokasikuliner')),
            ],
        ),
        migrations.CreateModel(
            name='Ulasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pengulas', models.CharField(max_length=50)),
                ('rating', models.IntegerField(default=1)),
                ('komentar', models.TextField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('lokasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ulasan', to='kuliner.lokasikuliner')),
            ],
        ),
    ]
