# Generated by Django 5.2.4 on 2025-07-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuliner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lokasikuliner',
            name='foto_utama',
            field=models.ImageField(blank=True, null=True, upload_to='lokasi_kuliner/'),
        ),
    ]
