# Generated by Django 5.2.4 on 2025-07-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuliner', '0002_lokasikuliner_foto_utama'),
    ]

    operations = [
        migrations.AddField(
            model_name='lokasikuliner',
            name='area',
            field=models.CharField(blank=True, choices=[('KOTA', 'Kota Yogyakarta'), ('SLEMAN', 'Sleman'), ('BANTUL', 'Bantul'), ('KULONPROGO', 'Kulon Progo'), ('GUNUNGKIDUL', 'Gunungkidul')], max_length=50),
        ),
    ]
